#!/usr/bin/env bash

if [ "$DOTFILES_GIT_URL" = "" ]; then
	fancy_warning "Since you are not cloning any DOTFILES, please make sure you manually update your `~/.zshrc` file."

else
	if [ ! -d $HOME/.dotfiles ]; then
		fancy_info "Installing Custom DotFiles..."

		# git clone $DOTFILES_GIT_URL ~/.dotfiles
		# sh ~/.dotfiles/scripts/install
	fi
fi
