#!/usr/bin/env bash

# https://github.com/robbyrussell/oh-my-zsh

if [ ! -d $HOME/.oh-my-zsh ]; then
	fancy_info "Installing Oh-My-Zsh..."
	# git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
	# cp $HOME/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
	# chsh -s $(which zsh)

	# Install ZSH-Autosuggestion plugin
	# git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
fi
