#!/usr/bin/env bash

if [ "$HOST_NAME" != "$(HOSTNAME)" ]; then
	fancy_info "Updating Host Name: $HOST_NAME"
	# sudo scutil --set HostName "$HOST_NAME"
	# sudo scutil --set LocalHostName "$HOST_NAME"
	# sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$HOST_NAME"
fi

if [ "$COMPUTER_NAME" != "$(scutil --get ComputerName)" ]; then
	fancy_info "Updating Computer Name: $COMPUTER_NAME"
	# sudo scutil --set ComputerName "$COMPUTER_NAME"
fi
