#!/usr/bin/env bash

# Force Homebrew to link current OpenSSL version (overrides osx default)
fancy_info "Linking Homebrew OpenSSL"
# openssl="$(brew list --versions | grep openssl)"
# ln -s "/usr/local/Cellar/openssl/${openssl: -6}/bin/openssl" "/usr/local/bin/openssl"

fancy_info "Updating Ruby Gems"
# Update and Install Gems
# gem update --system
# gem install bundler
# gem install rails
# gem install foreman

# Postgres Gem needs a little TLC
# gem install pg — —with-pg-config=/usr/local/bin/pg_config

# Start MySQL / MariaDB Service
if brew ls --versions mysql > /dev/null; then
  fancy_info "Starting MYSQL Service"
  # brew services start mysql
elif brew ls --versions mariadb > /dev/null; then
  fancy_info "Starting MariaDB Service"
  # brew servies start mariadb
fi

# Start Postgres Service
if brew ls --versions postgres > /dev/null; then
  fancy_info "Starting Postgres Service"
  # brew services start postgresql
fi

if brew ls --versions memcached > /dev/null; then
  fancy_info "Starting Memcached Service"
  # brew services start memcached
fi

# Start Redis Service
if brew ls --versions redis > /dev/null; then
  fancy_info "Setting up Redis Config"
  # Make sure redis configs exist and start service
  if [ ! -f /usr/local/etc/redis.conf ]; then
    echo
    # cp /usr/local/etc/redis.conf.default /usr/local/etc/redis.conf
  fi

  if [ ! -d /usr/local/var/db/redis ]; then
    echo
    # mkdir -p /usr/local/var/db/redis
  fi

  fancy_info "Starting Redis Service"
  # brew services start redis
fi

# Start RabbitMQ Service
if brew ls --versions rabbitmq > /dev/null; then
  fancy_info "Installing RabbitMQ Delayed Messages Plugin"
  # Install Rabbit Delayed Messages Exchange Plugin
  # wget -O /usr/local/opt/rabbitmq/plugins/abbitmq_delayed_message_exchange-0.0.1.ez https://bintray.com/rabbitmq/community-plugins/download_file?file_path=rabbitmq_delayed_message_exchange-0.0.1.ez

  # Enable It
  # /usr/local/opt/rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_delayed_message_exchange

  fancy_info "Updating Hostfile for RabbitMQ"
  # Attempt to update host file to correctly work with rabbitmq
  # echo "\n# RabbitMQ Host Settings\n" >> /etc/hosts
  # echo "\n127.0.0.1 ${HOST_NAME}\n" >> /etc/hosts
  # echo "\n127.0.0.1 ${HOST_NAME,,}\n" >> /etc/hosts
  # echo "\n::1 ${HOST_NAME}\n" >> /etc/hosts
  # echo "\n::1 ${HOST_NAME,,}\n" >> /etc/hosts

  # killall -HUP mDNSResponder

  fancy_info "Starting RabbitMQ Service"
  # brew services start rabbitmq
fi

# Start ElasticSearch Service
if brew ls --versions elasticsearch > /dev/null; then
  fancy_info "Starting ElasticSearch Service"
  # brew services start elasticsearch
fi

# Install Mix and Phoenix
if command -v elixir > /dev/null; then
  fancy_info "Installing Mix & Phoenix"
  # mix local.hex
  # mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
fi
