#!/usr/bin/env bash

# Installation for rbenv and chruby are not included here, since they are installed via homebrew.

# RVM: https://github.com/rvm/rvm
if [ "$RUBY_VERSION_MANAGER" = "rvm" ]; then
	fancy_info "Installing RVM..."
	# command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

	fancy_info "rvm: Installing latest ruby version..."
	# \curl -sSL https://get.rvm.io | bash -s stable --ruby
fi

if [ "$RUBY_VERSION_MANAGER" = "rbenv" ]; then
	fancy_info "rbenv: Installing latest ruby version..."
	# latest = rbenv install -l | grep -v - | tail -1
	# rbenv install $latest
	# rbenv global $latest
fi

if [ "$RUBY_VERSION_MANAGER" = "chruby" ]; then
	fancy_info "chruby: Installing latest ruby version..."
	# ruby-install --latest ruby
fi
