#!/usr/bin/env bash

# When using NVM to manage Node, Installing Yarn via homebrew breaks nvm/node installation.

# https://yarnpkg.com/lang/en/docs/install/#alternatives-tab

if ! command -v yarn > /dev/null; then
	fancy_info "Installing Yarn..."
	# curl -o- -L https://yarnpkg.com/install.sh | bash
fi
