#!/usr/bin/env bash

set -e

# ------------------------------------------------------------------------------
# :: Clone Bootstrap Repo (if !exist)
# ------------------------------------------------------------------------------
# export BOOTSTRAP_DIR=$HOME/bootstrapper
export BOOTSTRAP_DIR=$HOME/Workspace/bootstrapper

if [ ! -d $BOOTSTRAP_DIR ]; then
	echo "Cloning Bootstrapper Repo"
	# git clone master https://github.com/mikereinmiller/boostrapper.git "${BOOTSTRAP_DIR}"
fi

source $BOOTSTRAP_DIR/lib/functions

# ------------------------------------------------------------------------------
# :: Make sure all the config files have been created
# ------------------------------------------------------------------------------
source  $BOOTSTRAP_DIR/modules/setup/config
source  $BOOTSTRAP_DIR/modules/setup/brewfile

# ------------------------------------------------------------------------------
# :: Authenticate Sudo Upfront
# ------------------------------------------------------------------------------

# Ask for the administrator password upfront
# sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished
# while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ------------------------------------------------------------------------------
# :: Pre-Install Checks
# ------------------------------------------------------------------------------

# Before getting too far, make sure this is a Mac
if [ $(uname) != "Darwin" ]; then
	fancy_error "This setup script is only for MacOS"
	exit 1
fi

# Make sure command line tools have been installed
if ! command -v xcode-select > /dev/null; then
  fancy_info "Installing Command Line Tools..."
  # xcode-select --install
fi

# ------------------------------------------------------------------------------
# :: Source Each Module
# ------------------------------------------------------------------------------
fancy_echo "${PINK} ☕  You might want to grab a cup of coffee, this could take a little while...${NO_COLOR}"

modules=(
	osx_hostname
	oh_my_zsh
	node
	yarn
	homebrew
	ruby
	dotfiles
	post_install
	local_bootstrap
)

for module in "${modules[@]}"
do
	source "${BOOTSTRAP_DIR}/modules/$module"
done

tabs 4

fancy_echo "${PINK}Installation Summary ${NO_COLOR}"
if [ "$RUBY_VERSION_MANAGER" = "rbenv" ]; then
	echo "\t$(rbenv -v)"
fi

echo "\t$(ruby -v)"
# echo "nvm $(nvm --version)"
echo "\tnode $(node -v)"
echo "\tnpm $(npm -v)"

elx="\t$(elixir -v)"
echo "\t${elx: -12}"
echo "\t$(mix phoenix.new -v)"

fancy_success "☠️  Bootstrapper Setup Complete! Please restart your computer 🤘"
