#!/usr/bin/env bash

set -e

# ------------------------------------------------------------------------------
# :: Load Global Variables and Functions
# ------------------------------------------------------------------------------
export BOOTSTRAP_DIR=$HOME/Workspace/bootstrapper

# ------------------------------------------------------------------------------
# :: Clone Bootstrap Repo (if !exist)
# ------------------------------------------------------------------------------
if [ ! -d $BOOTSTRAP_DIR ]; then
	echo "Cloning Bootstrapper Repo"
	# git clone master https://github.com/mikereinmiller/boostrapper.git "${BOOTSTRAP_DIR}"
fi

source $BOOTSTRAP_DIR/lib/functions
source  $BOOTSTRAP_DIR/modules/setup/config
source  $BOOTSTRAP_DIR/modules/setup/brewfile

# Copy MacOS Configuration Script
cp $BOOTSTRAP_DIR/modules/setup/macos $BOOTSTRAP_DIR/macos.local
